#!/bin/bash

#SBATCH --job-name=evolution
#SBATCH --partition=depablo-sandyb
#SBATCH --output=gromacs-%j.out
#SBATCH --share
#SBATCH --output=zout
#SBATCH --error=zerr
#SBATCH --nodes=1

module load Anaconda2
python evolution.py
